const ErrorCodes = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_GENRE: "INVALID_GENRE",
    MUSIC_ALREADY_IN_PLAYLIST: "MUSIC_ALREADY_IN_PLAYLIST",
    PLAYLIST_NOT_FOUND: "PLAYLIST_NOT_FOUND",
    UNAUTHORIZED_ACTION: "UNAUTHORIZED_ACTION",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    EMPTY_PLAYLIST: "EMPTY_PLAYLIST",
    MUSIC_NOT_FOUND: "MUSIC_NOT_FOUND",
    INVALID_DATA: "INVALID_DATA",
    INVALID_NAME: "INVALID_NAME",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND"
  };
  
  module.exports = ErrorCodes;